### ISSUE TITLE
maximum length of a line

### ISSUE THREAD

**Issue by shuxiao9058** [Koihik/LuaFormatter#1]

**Comment by shuxiao9058** [comment]
as the function and the parameters in a line now. It hard to read the code while one line is very long,.

**Comment by shuxiao9058** [comment]
wrong format style like this:

``` lua
            -- jobData.limitCount = 1
            -- jobData.callbackURL = cfg.queryCallbackURL
            ngx_timer
                .at(0, jobqueue.JobProcess, jobData)
            -- jobqueue.Push2JobQueue(jobData)
```

**Comment by shuxiao9058** [comment]
> wrong format style like this:
> 
> ```lua
>             -- comment 1
>             ngx_timer
>                 .at(0, jobqueue.JobProcess, jobData)
>             -- comment2 this is a long text
> ```

format with commit 9bcfdf7ab1cbd8d31696b0ff2fa1fb3ab7448a95

**Comment by shuxiao9058** [comment]
```
column_limit: 80

indent_width: 4

continuation_indent_width: 4
# indent: '    '

# table separator, ',' or ';'
table_sep: ','

# add a extra separator at the end of table
extra_sep_at_table_end: false

# # allow format simple function to one-line
# # keep_simple_function_one_line: false
# keep_simple_block_one_line: false

# allow format simple table to one-line
keep_simple_table_one_line: true

# chop_down_parameter: 80

# chop_down_function: 120

# chop_down_table: 80

# chop down parameter if characters of parameter >= 50 (without white space)
chop_down_parameter: 50

# chop down block if characters of block >= 50 (without white space)
chop_down_block: 50

# chop down table if characters of table >= 50 (without white space)
chop_down_table: 50

# keep simple block one line
keep_simple_block_one_line: true

align_args: true

break_after_functioncall_lp: false

break_before_functioncall_rp: false

align_parameter: true

break_after_functiondef_lp: false

break_before_functiondef_rp: false

align_table_field: true

break_after_table_lb: true

break_before_table_rb: true

chop_down_kv_table: true

break_after_operator: true
```

**Comment by shuxiao9058** [comment]
wrong format with commit ea4f0d586a4f2a42e03ff7e2036bf56f224e7d17

``` lua
if true then
    if true then
        ngx
            .log(ngx_ERR,
                 'test string' .. "failed to create timer: " .. (err or 'nil'))
    end
end
```

**Comment by Koihik** [comment]
> wrong format with commit [ea4f0d5](https://github.com/Koihik/LuaFormatter/commit/ea4f0d586a4f2a42e03ff7e2036bf56f224e7d17)
> 
> ```lua
> if true then
>     if true then
>         ngx
>             .log(ngx_ERR,
>                  'test string' .. "failed to create timer: " .. (err or 'nil'))
>     end
> end
> ```

This is a strategic issue.
The priority of `function call` itself is higher than the priority of `parameters`.
When visit the `log` method, the entire statement is `.log(ngx_ERR, 'test string' .. "failed to c timer: " .. (err or 'nil'))`, less than column_limit. But plus the previous indent and `ngx`, it exceeds the limit, so break in front of `.log`.

Consider another scenario:
```lua
-- Break before `function call`, this looks good
some_var:position(x, y):click(function(v) v:hide() end):rotate(120)
    :clip(xxxx, yyyy, zzzz, aaaa)

-- Break in parameters, this looks strange
some_var:position(x, y):click(function(v) v:hide() end):rotate(120):clip(xxxx,
    yyyy, zzzz, aaaa)
```

The strategy of where to wrap should be smarter.
You can open a new issue. I think it's not easy to fix it.
