### ISSUE TITLE
format crash

### ISSUE THREAD

**Issue by yingnierxiao** [Koihik/LuaFormatter#112]
0   libsystem_kernel.dylib        	0x00007fff6da0e33a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6dacae60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff6d995808 abort + 120
3   libc++abi.dylib               	0x00007fff6abf5458 abort_message + 231
4   libc++abi.dylib               	0x00007fff6abe68a7 demangling_terminate_handler() + 238
5   libobjc.A.dylib               	0x00007fff6c7215b1 _objc_terminate() + 104
6   libc++abi.dylib               	0x00007fff6abf4887 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff6abf71a2 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	0x00007fff6abf7169 __cxa_throw + 113
9   lua-format                    	0x00000001064f60b8 std::__1::__throw_range_error(char const*) + 56
10  lua-format                    	0x00000001064f412d antlrcpp::utf8_to_utf32(char const*, char const*) + 1437
11  lua-format                    	0x00000001064f3afa antlr4::ANTLRInputStream::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 106
12  lua-format                    	0x00000001064f5263 antlr4::ANTLRInputStream::load(std::__1::basic_istream<char, std::__1::char_traits<char> >&) + 115
13  lua-format                    	0x000000010645f1a3 lua_format(std::__1::basic_istream<char, std::__1::char_traits<char> >&, Config const&) + 99
14  lua-format                    	0x00000001064ad3e5 main + 9957
15  libdyld.dylib                 	0x00007fff6d8c6cc9 start + 1

**Comment by tammela** [comment]
How did you reproduce this?

**Comment by yingnierxiao** [comment]
if file content contain  �\138  —成�\152

**Comment by tammela** [comment]
Could you provide a sample script?

**Comment by yingnierxiao** [comment]
print("%.0f�\176")

**Comment by tammela** [comment]
@karanankit01 

Can you reproduce? Seems like an issue with unicode literal strings

**Comment by karanankit01** [comment]
Ok, I will look into it.

**Comment by Koihik** [comment]
@yingnierxiao Could you provide a file including this bug?

**Comment by yingnierxiao** [comment]
print("%.0f�\176")  copy this to lua file

**Comment by Koihik** [comment]
Formatter only accept UTF-8 encoded files.
