### ISSUE TITLE
macOS luarock install ask for make

### ISSUE THREAD

**Issue by tangorri** [Koihik/LuaFormatter#135]
I try to install via luarocks (installed with brew) on Mac 
but I got this `Build error: 'cmake' program not found`
I do need to install cmake, because that's not the default compiler on Mac,
anyway this may be explained in documentation

thanks for this project

**Comment by tammela** [comment]
@tangorri 
`brew install cmake` should solve your issue

**Comment by tangorri** [comment]
true, it fixed it, but that maybe good for newcomers to get that info in install guide

**Comment by tammela** [comment]
PRs are welcome!
