### ISSUE TITLE
Request: column_table_limit_kv

### ISSUE THREAD

**Issue by Nexela** [Koihik/LuaFormatter#144]
column_table_limit_kv

type: int, default: column_table_limit

The column limit of each line of a k = vtable. Default value the same as column_table_limit value.

This will allow me to keep my arrays on a longer line but split up dictionary mappings

**Comment by tammela** [comment]
Could you provide an example of before/after?

**Comment by Nexela** [comment]
before
```lua
local a = {"one"', "two", "three"}
local b = {one = true, two = true, three = true}
```
column_table_limit = 40
column_table_limit_kv = 10

After
```lua
local a = {"one"', "two", "three"}
local b = {
  one = true,
  two = true,
  three = true
}
```

**Comment by tammela** [comment]
same as https://github.com/Koihik/LuaFormatter/issues/98

**Comment by Nexela** [comment]
Not quite the same,   column_table_limit affects both dictionary and array type tables.
```lua
column_limit: &1 120
indent_width: 4
continuation_indent_width: 4
align_table_field: false
break_after_table_lb: true
break_before_table_rb: true
column_table_limit: 30
chop_down_table: false
chop_down_kv_table: true
```

Input / Expected Output column_table_limit_kv=10, column_table_limit = 120:
```lua
local a = {"one", "one", "one", "one", "one", "one", "one", "one", "one", "one", "one", "one", "one", "one", "one"}

local blacklist_types = {
    ['item-request-proxy'] = true,
    ['rocket-silo-rocket'] = true,
    ['resource'] = true,
    ['construction-robot'] = true,
    ['logistic-robot'] = true,
    ['rocket'] = true,
    ['tile-ghost'] = true,
    ['item-entity'] = true
}

local oblong_entities = {
    ['arithmetic-combinator'] = true,
    ['decider-combinator'] = true,
    ['pump'] = true
}
```

Output: with column_table_limit=30
```lua
local a = {
    'one', 'one', 'one',
    'one', 'one', 'one',
    'one', 'one', 'one',
    'one', 'one', 'one',
    'one', 'one', 'one'
}

local blacklist_types = {
    ['item-request-proxy'] = true,
    ['rocket-silo-rocket'] = true,
    ['resource'] = true,
    ['construction-robot'] = true,
    ['logistic-robot'] = true,
    ['rocket'] = true,
    ['tile-ghost'] = true,
    ['item-entity'] = true
}

local oblong_entities = {
    ['arithmetic-combinator'] = true,
    ['decider-combinator'] = true,
    ['pump'] = true
}
```

Output: with colum_table_limit=120
```lua
local a = {'one', 'one', 'one', 'one', 'one', 'one', 'one', 'one', 'one', 'one', 'one', 'one', 'one', 'one', 'one'}

local blacklist_types = {
    ['item-request-proxy'] = true,
    ['rocket-silo-rocket'] = true,
    ['resource'] = true,
    ['construction-robot'] = true,
    ['logistic-robot'] = true,
    ['rocket'] = true,
    ['tile-ghost'] = true,
    ['item-entity'] = true
}

local oblong_entities = {['arithmetic-combinator'] = true, ['decider-combinator'] = true, ['pump'] = true}
```

**Comment by chirag-d11** [comment]
Hi @Nexela is there any update on this? A new setting for KV tables is desirable as KV tables read better if they are chopped down, while Normal tables read better if multiple rows are aligned (with more than one item in a row).
Since chop down settings are different for normal and KV tables, it would make sense to add a separate config for line limit for KV tables. 
Is there any plan to work on this?

**Comment by SuperSandro2000** [comment]
I wouldn't mind if the line breaks in tables where kept. If I decided to put line breaks after each first level table entry then it should be possible to keep those and not reformat them to one line if the column width happens to be shorter.

Lines should really only be reformatted if it is longer than configured not shorter.
