### ISSUE TITLE
column_limit is not considered when column_table_limit is enabled

### ISSUE THREAD

**Issue by psycho-neon** [Koihik/LuaFormatter#151]
`column_limit` is overridden and not followed  when `column_table_limit` is declared. 

Tables are formatted correctly, but other non-table codes are also affected with whatever length is declared on the `column_table_limit`

See screen shot below as an example:

**Config:** 
https://prnt.sc/vj8p3u

**Example 1 without column_table_limit:**
https://prnt.sc/vj8phs

**Example 2 with column_table_limit:**
https://prnt.sc/vj8pxe
Other codes are formatted to length whichever the value of the `column_table_limit` is

**Comment by chirag-d11** [comment]
Observing the same issue. column_limit should everywhere except inside tables, where column_table_limit should be applied. Which does not seem to be the case.

**Comment by chirag-manwani** [comment]
@Koihik Any update on this? Can replicate this bug on MacOS with latest release.
Also the column length for both normal code (functions, local variable declarations) and table is set to whatever is defined later in the lua-format file. 
So if column_limit is defined later the tables are not chopped. even if chop down kv table is set to true
And if column_table_limit is defined later then everything is formatted using this value of.
