### ISSUE TITLE
What about add support for vim?

### ISSUE THREAD

**Issue by andrejlevkovitch** [Koihik/LuaFormatter#16]
It's very simple - I just get `clang-format.py` and rewrite the script for LuaFormatter. After this I add several lines in my `.vimrc` and all works. It'll be nice, if you add the repo in your README.md: [vim-lua-format](https://github.com/andrejlevkovitch/vim-lua-format)

**Comment by Koihik** [comment]
Thank you for contributing, feel free to open a PR adding your vim-support project to README.
