### ISSUE TITLE
Entire document no longer formats.

### ISSUE THREAD

**Issue by odevices** [Koihik/LuaFormatter#161]
The context menu item, 

> "Format Document" (Ctrl+Shift+I)

and the workspace/user setting 

> "editor.formatOnSave": true

no longer have any effect in v1.3.7.  If I revert to v1.3.6 then everything works again.

**Comment by odevices** [comment]
Here is the contents of my LuaFormatter config file:

> indent_width: 2
> extra_sep_at_table_end: false
> keep_simple_function_one_line: false
> keep_simple_table_one_line: true
> chop_down_kv_table: false
> break_after_table_lb: true
> break_before_table_rb: true
> column_table_limit: 0

And the relevant sections of my settings.json

>   "vscode-lua-format.configPath": ".vscode/lua-format.config",
>   "editor.formatOnSave": true,

**Comment by Yamsha75** [comment]
Try `column_table_limit: 1`. I used your config and this fixed it for me.

**Comment by odevices** [comment]
> Try `column_table_limit: 1`. I used your config and this fixed it for me.

It does seem to make it do something again but it the formatting is all broken.  It seems to apply the column_table_limit to everything, not just tables now.

**Comment by Yamsha75** [comment]
If you could provide some example source code before and after parsing using your config in addition to expected results, I think this issue could be looked into

**Comment by odevices** [comment]
Hmm.  Updating to the v1.3.8 of the vscode-lua-format plugin fixed it.

I think I was confused by the version of the vscode-lua-format plugin and the version LuaFormatter not corresponding.  As of v1.3.8 of the vscode-lua-format plugin (which finally seems to use v1.3.6 of LuaFormatter) everything works as expected with a default config.

Thanks for your time!
