### ISSUE TITLE
Lua version support

### ISSUE THREAD

**Issue by vadi2** [Koihik/LuaFormatter#170]
Thanks for the really nice tool!

Which Lua versions are supported? I see no mention of this anywhere.

**Comment by tammela** [comment]
Lua's grammar is really stable and somewhat 'backwards' compatible.
5.3 and 5.4 for sure. 5.1 and 5.2 I would say are good as well, but I
didn't test those myself.

Em ter., 16 de mar. de 2021 às 03:22, Vadim Peretokin <
***@***.***> escreveu:

**Comment by vadi2** [comment]
Thanks!
