### ISSUE TITLE
Setup "--no-break-after-functioncall-lp" not working?

### ISSUE THREAD

**Issue by ray-x** [Koihik/LuaFormatter#186]
Before format
```lua  
self.buf, self.win, self.buf_closer = floatbuf({
        win_width = self.rect.width,
        win_height = self.rect.height,
        x = self.rect.pos_x,
        y = self.rect.pos_y,
        loc = loc,
        prompt = self.prompt,
        enter = opts.enter,
        ft = opts.ft,
        syntax = opts.syntax,
        relative = opts.relative
      })
```

After format:
```lua  
self.buf, self.win, self.buf_closer = floatbuf(
                                            {
        win_width = self.rect.width,
        win_height = self.rect.height,
        x = self.rect.pos_x,
        y = self.rect.pos_y,
        loc = loc,
        prompt = self.prompt,
        enter = opts.enter,
        ft = opts.ft,
        syntax = opts.syntax,
        relative = opts.relative
      })
```

I think I can accept 
```lua  
self.buf, self.win, self.buf_closer = floatbuf({
```
Or alternatively
```lua  
self.buf, self.win, self.buf_closer = floatbuf(
    {
       .....
    }
)
```

**Comment by jinwenhua** [comment]
I sorry, how about this, still not working
**assert(found_line_index < #frame.lines, 'invalid run data |' .. dumpInfo(
    {
        frame = frame,
        cursor = cursor,
        found_line_index = found_line_index,
        found_run = found_run,
        props = inputview_props()
    }))**

**Comment by Koihik** [comment]
> I sorry, how about this, still not working
> 
> `assert(found_line_index < #frame.lines, 'invalid run data |' .. dumpInfo( { frame = frame, cursor = cursor, found_line_index = found_line_index, found_run = found_run, props = inputview_props() })) `

Seems works well with default config:
```lua
assert(found_line_index < #frame.lines, "invalid run data |" .. dumpInfo({
    frame = frame,
    cursor = cursor,
    found_line_index = found_line_index,
    found_run = found_run,
    props = inputview_props()
}))

```

**Comment by jinwenhua** [comment]
I set the limit column equal 120



---Original---
From: ***@***.***&gt;
Date: Wed, May 19, 2021 20:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Koihik/LuaFormatter] Setup "--no-break-after-functioncall-lp" not working? (#186)




  
I sorry, how about this, still not working
 
assert(found_line_index < #frame.lines, 'invalid run data |' .. dumpInfo( { frame = frame, cursor = cursor, found_line_index = found_line_index, found_run = found_run, props = inputview_props() })) 
  
Seems works well with default config:
 assert(found_line_index < #frame.lines, "invalid run data |" .. dumpInfo({     frame = frame,     cursor = cursor,     found_line_index = found_line_index,     found_run = found_run,     props = inputview_props() }))

**Comment by jinwenhua** [comment]
It works! I sorry, my mistake, i did test it under the new version. the example code provided by ray-x works in my vscode, so I thought it should works with my code
