### ISSUE TITLE
chop_down_kv_table 选项生效问题

### ISSUE THREAD

**Issue by yinfei8** [Koihik/LuaFormatter#195]
当chop_down_kv_table设定为，一行的内容不超过列设定时候，如下：
-- chop_down_kv_table: true
x = {
    k1 = v1,
    k2 = v2
}

会格式化为：
-- chop_down_kv_table: true
x = {k1 = v1, k2 = v2}

**Comment by macias0** [comment]
Still not working in 1.3.6 version.
