### ISSUE TITLE
Uncorrect align of arguments

### ISSUE THREAD

**Issue by andrejlevkovitch** [Koihik/LuaFormatter#22]
I have problem with uncorrect formatting function arguments.
My config file:
```
column_limit: 80
use_tab: true
indent_width: 1
continuation_indent_width: 1
keep_simple_block_one_line: false
align_args: false
break_after_functioncall_lp: false
break_before_functioncall_rp: false
align_parameter: false
break_after_functiondef_lp: false
break_before_functiondef_rp: false
align_table_field: false
break_after_table_lb: false
break_before_table_rb: false
chop_down_kv_table: true
table_sep: ','
extra_sep_at_table_end: true
break_after_operator: true
```

This is how work now:
```lua
function tmp()
	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
												november)
	local body, mime = cache_images:get(config.CACHE.IMAGES_KEY_PREFIX .. cid ..
																																						type, beta, charlie)

end
```

But, of course, it is wrong. I think, I found wrong line:
```c++
// FormatVisitor.cpp:715
        firstArgsIndent = cur_columns() - indent_ - indentForAlign_;
```
Why here uses `cur_columns()`? I just remove it:
```c++
        firstArgsIndent = indent_ - indentForAlign_;
```
And now code looks like:
```lua
function tmp()
	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
			november)
	local body, mime = cache_images:get(config.CACHE.IMAGES_KEY_PREFIX .. cid ..
			type, beta, charlie)

end
```

**Comment by andrejlevkovitch** [comment]
And also, I think, `716` and `718` lines in `FormatVisitor.cpp` is also not correct, because it is not new line, but continious line.

**Comment by Koihik** [comment]
This bug has been fixed by https://github.com/Koihik/LuaFormatter/pull/21

**Comment by andrejlevkovitch** [comment]
Bug was be fixed in function defenition, but here is function call. Anyway I use latest version of LuaFormatter

**Comment by Koihik** [comment]
> Bug was be fixed in function defenition, but here is function call. Anyway I use latest version of LuaFormatter

The reason for the bug is that the aligned indent was added multiple times. 
#21 should fix this problem in all places. If you still have this problem elsewhere, please provide a code example. If not, I will close this issue.

**Comment by andrejlevkovitch** [comment]
In first message I paste code example and config file, which I uses for formatting.

**Comment by andrejlevkovitch** [comment]
Thank, now it looks better, but, I think, here is still is bug. Look: this is how looks before fix:
```lua
function tmp()
	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
												november)
	local body, mime = cache_images:get(config.CACHE.IMAGES_KEY_PREFIX .. cid ..
																																						type, beta, charlie)

end
```
and how it looks now:
```lua
function tmp()
	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
					november)
	local body, mime = cache_images:get(config.CACHE.IMAGES_KEY_PREFIX .. cid ..
											type, beta, charlie)

end

```
Here I used settings file from my first message. Removing `line 715` from `FormatVisitor.cpp`, I think, fixes the problem. Output looks like:
```lua
function tmp()
	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
		november)
	local body, mime = cache_images:get(config.CACHE.IMAGES_KEY_PREFIX .. cid ..
		type, beta, charlie)

end

```

**Comment by Koihik** [comment]
> Thank, now it looks better, but, I think, here is still is bug. Look: this is how looks before fix:
> 
> ```lua
> function tmp()
> 	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
> 												november)
> 	local body, mime = cache_images:get(config.CACHE.IMAGES_KEY_PREFIX .. cid ..
> 																																						type, beta, charlie)
> 
> end
> ```
> 
> and how it looks now:
> 
> ```lua
> function tmp()
> 	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
> 					november)
> 	local body, mime = cache_images:get(config.CACHE.IMAGES_KEY_PREFIX .. cid ..
> 											type, beta, charlie)
> 
> end
> ```
> 
> Here I used settings file from my first message. Removing `line 715` from `FormatVisitor.cpp`, I think, fixes the problem. Output looks like:
> 
> ```lua
> function tmp()
> 	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
> 		november)
> 	local body, mime = cache_images:get(config.CACHE.IMAGES_KEY_PREFIX .. cid ..
> 		type, beta, charlie)
> 
> end
> ```

You can change tab_width to 8 in config.

**Comment by andrejlevkovitch** [comment]
> You can change tab_width to 8 in config.

And how it can fix problem? Look, here:
```lua
function tmp()
	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
					november)
```

between begininf of second and begining of third line is 4 tabs. But in config file `align_args: false` (and other align properties also set for `false`). So, here have to only one tab (because set property `continuation_indent_width: 1`)

**Comment by Koihik** [comment]
> > You can change tab_width to 8 in config.
> 
> And how it can fix problem? Look, here:
> 
> ```lua
> function tmp()
> 	my_fund = alfa(beta, charlie, gamma, echo, foxtrot, lima, kilo, india, juliet,
> 					november)
> ```
> 
> between begininf of second and begining of third line is 4 tabs. But in config file `align_args: false` (and other align properties also set for `false`). So, here have to only one tab (because set property `continuation_indent_width: 1`)

Because this is an assignment statement. So LuaFormatter will try to align the last args `november` with the function call `alfa`. 
First tab is for function define. 
The second and third tab is for align `alfa`(it's at position 10 relative to start of assignment statement, and tab width is 8, so need 2 tabs). 
And the last tab is for `continuation_indent_width`.

**Comment by andrejlevkovitch** [comment]
IMHO, when we set align to false, then second line (with `november`) have to begining from position: `begining of first line + continuation_indent_width`. Alignment not from begining (when we align by function call) is very big problem, when we use tabs, because tabs can be displayed like diverse number of spaces, so we have diverse formats in diverse computers (where is using tab width as 1, 2, 4 or 8). 

PS I do not like use tabs, and think that is very bad practice (problem, described above, never be with spaces), but, for some reason, I have to use this now.

**Comment by Koihik** [comment]
> IMHO, when we set align to false, then second line (with `november`) have to begining from position: `begining of first line + continuation_indent_width`. Alignment not from begining (when we align by function call) is very big problem, when we use tabs, because tabs can be displayed like diverse number of spaces, so we have diverse formats in diverse computers (where is using tab width as 1, 2, 4 or 8).
> 
> PS I do not like use tabs, and think that is very bad practice (problem, described above, never be with spaces), but, for some reason, I have to use this now.

I realized that aligning with tabs was a mistake. Maybe we should use tab just for indent & continuation indent, and still use whitespace for aligning.

**Comment by evolbug** [comment]
Issue is present when `break_after_functioncall_lp: true` tables ignore continuation depth
```lua
local test = w.e.new(
                 table.extend(
                     {
            position = {x = 0, y = 0},
            velocity = {x = 0, y = 0},
            physics = {other = -1},
            input = {up = false, down = false, left = false, right = false},
            size = {width = 0, height = 0},
            drawable = {alpha = 1, depth = 1, draw = false}
        }, init
                 )
             )
```
Expected this:
```lua
local test = w.e.new(
                 table.extend(
                     {
                        position = {x = 0, y = 0},
                        velocity = {x = 0, y = 0},
                        physics = {other = -1},
                        input = {up = false, down = false, left = false, right = false},
                        size = {width = 0, height = 0},
                        drawable = {alpha = 1, depth = 1, draw = false}
                     }, init
                 )
             )
```
However, I think there should be an additional setting for indenting against function name behaviour e.g. `align_args_to_functioncall`, which by default should be off as it wastes a lot of space. By default I would expect it to align like this: 
```lua
local test = w.e.new(
    table.extend(
        {
            position = {x = 0, y = 0},
            velocity = {x = 0, y = 0},
            physics = {other = -1},
            input = {up = false, down = false, left = false, right = false},
            size = {width = 0, height = 0},
            drawable = {alpha = 1, depth = 1, draw = false}
        }, init
    )
)
```
