### ISSUE TITLE
yaml-cpp: error at line 24, column 21: bad conversion

### ISSUE THREAD

**Issue by ryanford** [Koihik/LuaFormatter#226]
I get the error `yaml-cpp: error at line 24, column 21: bad conversion` on Ubuntu 20.04 from the luarocks version and building from source from the repo.

**Comment by simonhoyos** [comment]
Any updates on this one? I'm having the same issue

**Comment by sarman** [comment]
Ubuntu 20.04 luarocks, the same…

**Comment by russmatney** [comment]
I hit this after copy-pasting the default `.lua-format` from the readme into my project - it seems to be caused by the line:

```
column_table_limit: column_limit
```

Removing that line fixes this for now, and maybe hints at what the underlying issue is?
