### ISSUE TITLE
Disable formatting for a line or block

### ISSUE THREAD

**Issue by bofm** [Koihik/LuaFormatter#26]
Hi! Is it possible to disable auto-formatting for a block?
Something like this:
```lua
-- fmt: off
local paths = {
    root .. "/app/?.lua",
    root .. "/?.lua",
    root .. "/?/init.lua",
    root .. "/app/?/init.lua",
    root .. "/.rocks/share/lua/5.1/?.lua",
    root .. "/.rocks/share/lua/5.1/?/init.lua",
}
```

**Comment by Koihik** [comment]
You can manually insert some line comment to force break line.
example:
```lua
local paths = {
    root .. "/app/?.lua", --
    root .. "/?.lua", --
    root .. "/?/init.lua", --
    root .. "/app/?/init.lua", --
    root .. "/.rocks/share/lua/5.1/?.lua", --
    root .. "/.rocks/share/lua/5.1/?/init.lua" --
}
```

However, Disable format for a block may also support in the future.

**Comment by treahard** [comment]
We would also like this feature with perhaps "-- fmt: off" and then "--fmt: on" although the forced break line is working well too (thanks!).

**Comment by celediel** [comment]
Forcing line break is all well and good, but the formatter still changes whitespace in the beginning of a line.

I have a function that I tried this trick with,
`local function checkNPC(npc)
    return not config.IsBlocked[npc.object.baseObject.id] and --
           not config.IsBlocked[npc.object.baseObject.sourceMod] and --
           not npc.object.isGuard and --
           not mwscript.getSpellEffects({reference = npc, spell = "vampire sun damage"}) and --
           not mwscript.getSpellEffects({reference = npc, spell = "werewolf vision"}) and --
           not npc.object.class.id ~= "Dreamers" --
end`

and the formatter turns it into
`local function checkNPC(npc)
    return not config.IsBlocked[npc.object.baseObject.id] and --
    not config.IsBlocked[npc.object.baseObject.sourceMod] and --
    not npc.object.isGuard and --
    not mwscript.getSpellEffects({reference = npc, spell = "vampire sun damage"}) and --
               not mwscript.getSpellEffects({reference = npc, spell = "werewolf vision"}) and --
    not npc.object.class.id ~= "Dreamers" --
end`

As you can see, not entirely desirable!

I hope support for selective disabling can be added in the future!

**Comment by MonkeyKingMKY** [comment]
like the formater of clang-format
// clang-format off
// clang-format on

is really usaful

hope support this feature
