### ISSUE TITLE
windows build for Release and Actions artifact

### ISSUE THREAD

**Issue by shikulja** [Koihik/LuaFormatter#292]
(I would like to check the formatting parameters locally on the PC before adding it to workflow)

**Comment by emako** [comment]
[lua-format.zip](https://github.com/Koihik/LuaFormatter/files/14800201/lua-format.zip)
Here a binary file is cached and provided to users who try this software.

**Comment by shikulja** [comment]
@emako thanks, I'll definitely try it

**Comment by emako** [comment]
The bin files are published to vs marketplace https://marketplace.visualstudio.com/items?itemName=Koihik.vscode-lua-format
[Download Extension](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Koihik/vsextensions/vscode-lua-format/1.3.8/vspackage)
