### ISSUE TITLE
No newline after multiline comment

### ISSUE THREAD

**Issue by surgura** [Koihik/LuaFormatter#32]
If a statement is right after a multiline comment, the statement will be formatted right after the comment ends.
```lua
--[[
--
--]]
local lgi = 3
```
Becomes
```lua
--[[
--
--]] local lgi = 3
```

This does not seem like intended behaviour to me.

**Comment by surgura** [comment]
A workaround for this issue is ending a multiline comments with `--]] --`

**Comment by Koihik** [comment]
> A workaround for this issue is ending a multiline comment with `--]] --`

`--[[ ]]` is inline comment style. like `function --[[ comment ]] abc() end`.
The AST node surround it will be as close together as possible after format because it can be insert at anywhere.
So if we need to comment multiple lines, just choose multiple lines and use the comment function of editor. It will insert `--` before each line.

**Comment by surgura** [comment]
Okay, seems reasonable. How do you feel about having two distinct cases:
- keep the newline if it is already present after `--]]`
- don't add the newline if it was not present after `--]]`

**Comment by surgura** [comment]
So `--]]\n` would be a different token to `--]]` in the ast

**Comment by Koihik** [comment]
> So `--]]\n` would be a different token to `--]]` in the ast

'\n' will be ignored in AST. The information that there are blank char or not has been lost after lexer.

**Comment by dvdvideo1234** [comment]
Lua `--[[` and  `]]` tokens are the same as `--[===[` and `]===]` ( notice the `=` signs count are the same in both tokens ). The `=` signs count may vary in length depending on your multiple line comment or whenever or not you are commenting `[` and `[` tokens. For example `--[=[` and `]=]` are also valid, however `--[==[` and `]=]` are not as they contain different set of `=`s.

**Comment by BillScott1024** [comment]
So How To Fix The Problem??

**Comment by surgura** [comment]
> So How To Fix The Problem??

Scroll up. There are two answers in the thread and the thread is short.

**Comment by BillScott1024** [comment]
> > 那么如何解决问题？
> 
> 向上滑动。线程中有两个答案，线程很短。

Fine, solved , thanks
