### ISSUE TITLE
[request] post on https://luarocks.org/

### ISSUE THREAD

**Issue by tammela** [Koihik/LuaFormatter#41]
I think this is a great tool for the Lua community. One that has been lacking for a long time!!

Please consider posting it on luarocks and perhaps a mailing list announcement as well?

**Comment by Koihik** [comment]
I don't use lua or luarocks often, but as far as I know luarocks is a lua package manager. This project is written in c++.
Well, it's possible to provide a wrapper package written in lua for lua-format binary. But I just think it's seems no sense to format lua code in lua.

**Comment by tammela** [comment]
> I don't use lua or luarocks often, but as far as I know luarocks is a lua package manager. This project is written in c++.
> Well, it's possible to provide a wrapper package written in lua for lua-format binary. But I just think it's seems no sense to format lua code in lua.

Hi Koihik,
Luarocks it's a package manager for tools and libraries in the Lua eco system. This includes packages written in any language basically, not just pure Lua or C/C++.

I can "maintain" the package in luarocks if you think it's too much for you

**Comment by Koihik** [comment]
> > I don't use lua or luarocks often, but as far as I know luarocks is a lua package manager. This project is written in c++.
> > Well, it's possible to provide a wrapper package written in lua for lua-format binary. But I just think it's seems no sense to format lua code in lua.
> 
> Hi Koihik,
> Luarocks it's a package manager for tools and libraries in the Lua eco system. This includes packages written in any language basically, not just pure Lua or C/C++.
> 
> I can "maintain" the package in luarocks if you think it's too much for you

Yes, all contributions are welcome.
