### ISSUE TITLE
OSX 10.14 build fails

### ISSUE THREAD

**Issue by stuta** [Koihik/LuaFormatter#52]
When I build with cmake I get this error:

```bash
Run Build Command(s):/usr/bin/make cmTC_1d318/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_1d318.dir/build.make CMakeFiles/cmTC_1d318.dir/build
Building CXX object CMakeFiles/cmTC_1d318.dir/fs.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14   -std=c++1z -o CMakeFiles/cmTC_1d318.dir/fs.cpp.o -c /Users/pasi/installed/Lua/LuaFormatter/test/cpp17/fs.cpp
/Users/pasi/installed/Lua/LuaFormatter/test/cpp17/fs.cpp:7:21: error: 'path' is unavailable: introduced in macOS 10.15
   std::filesystem::path current = ".";
```

**Comment by tammela** [comment]
The C++ 17 filesystem library was introduced in macOS 10.15.

I believe you will only be able to run this on macOS Catalina

**Comment by tammela** [comment]
Or you could use brew's llvm 9 https://formulae.brew.sh/formula/llvm

**Comment by stuta** [comment]
> Or you could use brew's llvm 9 https://formulae.brew.sh/formula/llvm

I installed llvm 9 and did set env variables, but I could not get it to compile. CMakeCache.txt shows /usr/local/Cellar/llvm/9.0.0_1/bin paths and CMAKE_MODULE_LINKER_FLAGS:STRING=-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib. It still shows same error.

 I have 32 bit work programs so I can't go to Catalina.

**Comment by tammela** [comment]
There's a bit of shenanigans you will have to make.

Make sure this is env when you configure the cmake build. If there's any cache you must delete it.

```bash
export LDFLAGS=-L/usr/local/opt/llvm/lib
export CPPFLAGS=-mmacosx-version-min=10.15 -I/usr/local/opt/llvm/include
export PATH=/usr/local/opt/llvm/bin:$PATH
```

Configure cmake with the following invocation

```bash
cmake -E env LDFLAGS="$LDFLAGS" CXXFLAGS="CPPFLAGS" cmake ..
```

I have tested it and it works,

have fun!

**Comment by stuta** [comment]
I had to run:

```bash
sudo xcode-select -s /Library/Developer/CommandLineTools
cmake -E env LDFLAGS="-L/usr/local/opt/llvm/lib" CXXFLAGS="-mmacosx-version-min=10.15 -I/usr/local/opt/llvm/include" cmake ..
```

Running export ```export CPPFLAGS=-mmacosx-version-min=10.15 -I/usr/local/opt/llvm/include``` did not work because it contains spaces. Also ```export PATH``` is not needed. And builds are much faster with Ninja.
