### ISSUE TITLE
Change build instruction in README

### ISSUE THREAD

**Issue by DevAlone** [Koihik/LuaFormatter#63]
What about to change this:

```
git clone --recurse-submodules https://github.com/Koihik/LuaFormatter.git
cd LuaFormatter
cmake .
make
make install
```

To this:

```
git clone --recurse-submodules https://github.com/Koihik/LuaFormatter.git
cd LuaFormatter
mkdir build
cd build
cmake ../
make
make install
```

So that tests work, now they don't pass because it's trying to read files from the parent directory.

**Comment by tammela** [comment]
Perhaps the fix would be to not use relative paths in the test suite

**Comment by dnebauer** [comment]
Is this bug the reason my luarocks install fails with this error?

```
error: Server does not allow request for unadvertised object e1c9d5569dc4135babb9c81891d70a8ba8ed938c
Fetched in submodule path 'third_party/Catch2', but it did not contain e1c9d5569dc4135babb9c81891d70a8ba8ed938c. Direct fetching of that commit failed.

Error: Failed to fetch submodules.
```

**Comment by tammela** [comment]
No, luarocks internally uses a git command that should clone all submodules
commits as is. Github blocks this command on non tagged commits, so as a
requirement it is needed that all submodules must best in a tagged commit.

Unfortunately it looks like that something broke. After I caught this
problem myself I have double checked that all submodules were tagged.

As a workaround for now, you may install it following the `Build from
source` guide.

**Comment by dnebauer** [comment]
Thanks. I used devAlone's instructions above. I didn't try the recommended install instructions so I don't know if they would have worked or not.

I've tried the formatter on a mildly complex file (in vim using the andrejlevkovitch/vim-lua-format plugin) and it worked brilliantly! Thanks for this very useful tool.

**Comment by tammela** [comment]
> Thanks. I used devAlone's instructions above. I didn't try the recommended install instructions so I don't know if they would have worked or not.
> 
> I've tried the formatter on a mildly complex file (in vim using the andrejlevkovitch/vim-lua-format plugin) and it worked brilliantly! Thanks for this very useful tool.

Hi, I have tested the LuaRocks install and it seems it's working OK.

I'm planning to add a CI pipeline for LuaRocks so we can catch these kinds of build failures more easily. Thanks!

**Comment by stuta** [comment]
This is how I build this without luarocks in OSX.

```bash
mkdir build
cd build
cmake -E env LDFLAGS="-L/usr/local/opt/llvm/lib" CXXFLAGS="-mmacosx-version-min=10.15 -I/usr/local/opt/llvm/include" cmake ..
make
```

**Comment by tammela** [comment]
@Koihik please close this
