### ISSUE TITLE
Return non-zero status if formatting failed

### ISSUE THREAD

**Issue by comfortablynick** [Koihik/LuaFormatter#68]
Hi,

I use lua-format along with the vim plugin Neoformatter. I can't set vim to format on save because lua-format doesn't return an error code when formatting fails. If there is an error, I end up saving a blank file which is a problem! 

For example, if I'm missing a brace, I get this error message:

```
formatting: init.lua
line 317:0 missing '}' at 'local'
Input contains syntax errors
```
This will cause the vim format plugin to clear the buffer because it thinks lua-format has succeeded. 
Is it possible to return something other than zero if formatting fails?

**Comment by tammela** [comment]
Of course!

**Comment by tammela** [comment]
Merged fix, closing

**Comment by comfortablynick** [comment]
Thanks this works great!
