### ISSUE TITLE
Segfault encountered when formatting file

### ISSUE THREAD

**Issue by cp-shen** [Koihik/LuaFormatter#70]
Segfault encountered when formatting the file below
[input file](https://github.com/cp-shen/my-dotfiles-ZL/blob/master/.config/awesome/layout/left-panel/init.lua)

**Comment by cp-shen** [comment]
> Segfault encountered when formatting the file below
> [input file](https://github.com/cp-shen/my-dotfiles-ZL/blob/master/.config/awesome/layout/left-panel/init.lua)

The simple script below can reproduce this:


```lua
local t = {{},{}}

function t:func()
    return t
end

t:func()[1].key = true

print(t[1].key)
```

**Comment by tammela** [comment]
I was able to reproduce it, will take a look.

Thanks!

**Comment by tammela** [comment]
Looks like this line already raises the segfault.

```lua
t:func()[1].key = true
```

**Comment by tammela** [comment]
@cp-shen could you please test it with the patch?

thanks

**Comment by cp-shen** [comment]
My PC at home does not have the environment and tools to compile it. I will test it tomorrow at work.  The original file raised the error can be found [here](https://github.com/cp-shen/my-dotfiles-ZL/blob/master/.config/awesome/layout/left-panel/init.lua).

**Comment by cp-shen** [comment]
No segfault occurs on that file now. Looks like it is fixed.
