### ISSUE TITLE
LuaRocks install fails on 'third_party/Catch2'

### ISSUE THREAD

**Issue by dnebauer** [Koihik/LuaFormatter#82]
Install of a9aa804 (2020-01-11) using recommended command:

```
luarocks install --server=https://luarocks.org/dev luaformatter
```

fails with output:

```
error: Server does not allow request for unadvertised object e1c9d5569dc4135babb9c81891d70a8ba8ed938c
Fetched in submodule path 'third_party/Catch2', but it did not contain e1c9d5569dc4135babb9c81891d70a8ba8ed938c. Direct fetching of that commit failed.

Error: Failed to fetch submodules.
```

Reported first in #63 but that is about a different issue to this one. @tammela [noted](https://github.com/Koihik/LuaFormatter/issues/63#issuecomment-562866399):

> Luarocks internally uses a git command that should clone all submodules
commits as is. Github blocks this command on non tagged commits, so as a
requirement it is needed that all submodules must best in a tagged commit.
> 
> Unfortunately it looks like that something broke. After I caught this
problem myself I have double checked that all submodules were tagged.
> 
> As a workaround for now, you may install it following the `Build from
source` guide.

**Comment by tammela** [comment]
Hi!

Please update Luarocks to HEAD and try it again.

Thanks,
Pedro

**Comment by danlamanna** [comment]
Also experiencing this. Are we expected to be running master of luarocks?

**Comment by tammela** [comment]
Please use luarocks 3.3.0.

It was released yesterday.

Thank you!

**Comment by dnebauer** [comment]
Finally needed to re-install a module using luarocks (now at version 3.3.1). The error I reported in this issue no longer occurred and the module installed successfully.

Thanks.
