### ISSUE TITLE
Fails to format some escaped strings

### ISSUE THREAD

**Issue by Rerumu** [Koihik/LuaFormatter#83]
When I try to format code with the setting `double_quote_to_single_quote` set to true the formatting succeeds but breaks some escapes which cause unfinished string syntax errors.

Quick example:
```Lua
local a = "\\"
```
Which incorrectly formats to:
```Lua
local a = '\'
```

**Comment by tammela** [comment]
I will take a look.

Please provide more examples.

Thank you!

**Comment by Rerumu** [comment]
After some testing this happens to both `double_quote_to_single_quote` and `single_quote_to_double_quote`. When either is an enabled and a conversion takes place, if the string ends in two backslashes, one is removed. For example:
```Lua
local a = "text\\"
local b = 'text\\'
```

If you have `double_quote_to_single_quote` enabled in your format settings, `a` will be transformed into `'text\'` when expected behavior is `'text\\'`. Conversely, when `single_quote_to_double_quote` is enabled, `b` is formatted to `"text\"`, which is again wrong.

**Comment by tammela** [comment]
@Rerumu we merged a fix for this, could you please verify if it did work on your side?

**Comment by Rerumu** [comment]
Yes the issue seems to have been fixed.
