### ISSUE TITLE
Improvement for Logging

### ISSUE THREAD

**Issue by tammela** [Koihik/LuaFormatter#91]
In the `LOG_FUNCTION_*()` macros we always pass the function name as an argument.

This is not necessary since the C++ 11 standard adds an implicit declaration of the function name called `__func__`[1].

We shall leverage this in the macro expansion.

[1] https://stackoverflow.com/questions/4384765/whats-the-difference-between-pretty-function-function-func

**Comment by Akylzhan** [comment]
I can work on this issue but I need some help since I am quite new to programming.

As I understood I just need to change arguments of ```LOG_FUNCTION_BEGIN(function_name) ``` and ```LOG_FUNCTION_END(function_name) ``` in all functions to ```__func__```

**Comment by tammela** [comment]
No, the macro expands everytime you call it. So the idea is to replace all the uses of `function_name` with `__func__` *inside* the macros

**Comment by Akylzhan** [comment]
As I get it, we just need to remove ```arg``` and instead use ```__func__``` inside of the macros in order to just call ```LOG_FUNCTION_BEGIN()``` without arguments and still get function name?

**Comment by tammela** [comment]
Yes
