### ISSUE TITLE
chop_down_table and chop_down_kv_table not working

### ISSUE THREAD

**Issue by comedinha** [Koihik/LuaFormatter#98]
After last updates the functions chop_down_table and chop_down_kv_table is not working property.
Tested with versions 1.3.1 and 1.3.3.

With:
```
column_limit: 250
indent_width: 2
tab_width: 2
continuation_indent_width: 2
chop_down_table: true
chop_down_kv_table: true
```

Input:
```
test = {
  image = "test",
  list = {
    {
      ref = "testRef",
      tags = { "tagTest" },
      time = 10,

      materials = {
        {
          materialId = 123,
          count = 10
        }
      },
    },
  },
}
```

Output:
```
test = {image = 'test', list = {{ref = "testRef", tags = {"tagTest"}, time = 10, materials = {{materialId = 123, count = 10}}}}}
```

If column limit is set to 80 the output is:
```
test = {
  image = 'test',
  list = {
    {
      ref = "testRef",
      tags = {"tagTest"},
      time = 10,
      materials = {{materialId = 123, count = 10}},
    },
  },
}
```

**Comment by Koihik** [comment]
It seems works well. Do you want the output that chop down each table regardless of the column limit?

**Comment by comedinha** [comment]
Believe that this is how the system could work, or adding a column_table_limit would be useful.

**Comment by aganm** [comment]
I would also be interested in a `column_table_limit `.  I have `column_limit` to 80 but I want to my tables content to always break no matter what. I find it hard to read when many values are packed on one line.

**Comment by tammela** [comment]
@aganm @karanankit01 added this feature
